#!/bin/sh

change_volume() {
    amixer set Master "$1"
    anu=$(amixer get Master | awk '$0~/%/{print $5}' | tr -d '[]' |awk NR==1| awk 'BEGIN{RS="%\n"}1')
    #notify-send --expire-time=50 "Volume $anu"
    fn-notify vol $anu
}

main() {
    case "$1" in
      up)
         change_volume 2%+
         ;;
      down)
         change_volume 2%-
         ;;
      toggle)
	 change_volume toggle
	 ;;
     *)
         printf "volume <command>\n"
         printf "         up \n"
         printf "         down\n"
	 printf "	  toggle\n"
    esac
}

main "$@"
